version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
  apigateway:
    restart: always
    container_name: apigateway
    image: ${DOCKER_REGISTRY-}krkareportsapigateway
    environment:
        - TZ=${TZ}
    build:
      context: .
      dockerfile: Krka.Reports.ApiGateway/Dockerfile
    depends_on:
        - eventhub
    ports:
        - "10000:443"
    networks:
        - backend
  minapi:
    restart: always
    container_name: minapi
    image: ${DOCKER_REGISTRY-}krkareportsminapi
    environment:
        - TZ=${TZ}
    build:
      context: .
      dockerfile: Krka.Reports.Services.MinApi/Dockerfile
    depends_on:
        - eventhub
    ports:
        - "10001:443"
    networks:
        - backend
  eventhub:
    restart: always
    container_name: eventhub
    image: ${DOCKER_REGISTRY-}krkareportseventhub
    build:
      context: .
      dockerfile: Krka.Reports.EventHub/Dockerfile
    ports:
        - "11000:11000"
        - "12000:12000"
    networks:
        - backend
  servicesdemo:
    restart: always
    container_name: servicesdemo
    image: ${DOCKER_REGISTRY-}krkareportsservicesdemo
    build:
      context: .
      dockerfile: Krka.Reports.Services.Demo/Dockerfile
    depends_on:
        - eventhub
    networks:
        - backend
networks:
  backend:
    name: krkareports
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: krkareports